### ISSUE TITLE
please options support host  

### ISSUE THREAD

**Issue by ghost** [sakalx/useCaptcha#9]
https://github.com/sakalx/useCaptcha/issues/6

like  this :
```
let host = "www.recaptcha.net":

const [captchaRef, execute, response] = useCaptcha(sitekey, host=host);
```

**Comment by sakalx** [comment]
Hi stfenjobs,
well although it's good idea,
but different hosts using different API
this hook integrated specific with Google API.

Thank you.

**Comment by ghost** [comment]
hi @sakalx 

https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally

![image](https://user-images.githubusercontent.com/6580897/98005712-534ece80-1e2c-11eb-81ce-a8140a3fc2ad.png)

**Comment by sakalx** [comment]
hmm interesting will take a look closely over weekend,
thanks @stfenjobs for hint

**Comment by ghost** [comment]
thank you @sakalx

**Comment by sakalx** [comment]
@stfenjobs 
version: [1.0.4](https://www.npmjs.com/package/usecaptcha/v/1.0.4)
```js
useCaptcha(sitekey, { globally: true })
```

**Comment by ghost** [comment]
@sakalx   thank you very much
